### ISSUE TITLE
Needs an update for 0.7.15/0.7.16

### ISSUE THREAD

**Issue by YeapGuy** [minenite/paneltheme#2]
No one uses 0.7.13 today! This seriously needs an update!

**Comment by ethamitc** [comment]
@YeapGuy What do you mean, both myself and a quite popular hosting company I work for are running 0.7.13...

**Comment by icedmoca** [comment]
@YeapGuy I might try to push for an update but no promises. But for now 0.7.13 is a good working platform. But as Dane said, "Panel@0.7.17 and Daemon@0.6.13 have been released and fix a medium and a high severity security issue respectively. All users are encouraged to update as soon as possible to mitigate these issues." So I will try to update for you but this panel is mostly for my use only but others are welcome to use it too.
