### ISSUE TITLE
Different colour themes

### ISSUE THREAD

**Issue by Technofied** [minenite/paneltheme#4]
Hi there!

Loving the theme so far, however it would be nice that instead of purple UI/gradient perhaps you could have a few other colours. Perhaps a Navy Blue or Black that you could switch with somewhat ease?

Kind Regards,
Techno

**Comment by icedmoca** [comment]
Yes argon 2 is out! Some theme ideas I'll put into the works:

- Dark/Light mode.
- Custom color customization built into admin panel.
- Per user color customization permissions.
- Custom header image support.

**Comment by icedmoca** [comment]
Deprecated. ❌
