### ISSUE TITLE
No OOM Killer option, and problems when creating servers

### ISSUE THREAD

**Issue by tbringuier** [minenite/paneltheme#6]
Hi,
I just installed this theme and some servers can't install.
When i modify Build Configurations of others it can't because there is not the option OOM Kill.

Is it possible to add it ?

**Comment by Kas-tle** [comment]
I have made a PR to address this, but if need be you can modify build.blade.php as I have in this PR: https://github.com/minenite/paneltheme/pull/7.
Simply change the build.sh file to pull from my fork (https://github.com/Kas-tle/paneltheme) until the PR can be merged.

**Comment by tbringuier** [comment]
Thanks ;)
